/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import test from "./assets/models/test.glb";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(test);
  const { actions } = useAnimations(animations, group);

  const toggle = () => {
    actions.CylinderAction.isRunning()
      ? actions.CylinderAction.stop()
      : actions.CylinderAction.play();
  };

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
        scale={9.9}
        receiveShadow
      />
      <mesh
        castShadow
        name="Cylinder"
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.003"]}
        position={[0.78, 2.27, -0.77]}
        scale={[1, 2.36, 1]}
        onTrigger={(e) => toggle()}
      />
    </group>
  );
}

useGLTF.preload(test);
