/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations, softShadows } from "@react-three/drei";
softShadows();

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/test.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
        scale={9.9}
      />
      <mesh
        name="Cube"
        castShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.002"]}
        position={[-0.38, 2, 0]}
        onClick={(e) => actions.CubeAction.play()}
      />
    </group>
  );
}

useGLTF.preload("/test.glb");
